#!/usr/bin/env python3
# Embed the user-program flat binaries into a C header the kernel #includes.
# Each program is linked at 0x40000000 as a flat image (.text .rodata .data);
# the kernel loader zeroes the target pages first so .bss ends up zero.
import sys

progs = sys.argv[1:]
names = []
with open("../kernel/src/uprogs.inc", "w") as out:
    out.write("// AUTO-GENERATED by user/genprogs.py -- do not edit.\n")
    out.write("// Embedded user-program flat binaries (linked at 0x40000000).\n\n")
    for p in progs:
        data = open(p + ".bin", "rb").read()
        out.write("static const unsigned char uprog_%s[] = {" % p)
        out.write(",".join(str(b) for b in data))
        out.write("};\n")
        names.append(p)
    out.write("\ntypedef struct { const char *name; "
              "const unsigned char *bin; unsigned len; } uprog_t;\n")
    out.write("static const uprog_t uprogs[] = {\n")
    for p in names:
        out.write('  { "%s", uprog_%s, sizeof(uprog_%s) },\n' % (p, p, p))
    out.write("};\n")
    out.write("static const int nuprogs = %d;\n" % len(names))
print("genprogs: embedded", ", ".join(names))
